import { generateProtocolForPacient } from "protocols-generator";

jest.mock("uuid", () => {
  return {
    v4: () => {
      return "protocol generated by mock";
    },
  };
});

describe("calculator tests", () => {
  it("should work", async () => {
    const result = generateProtocolForPacient("Pedro", "Silva", true);

    expect(result).toEqual({
      priority: result.priority,
      date: result.date,
      pacient: result.pacient,
      protocol: "protocol generated by mock",
    });
  });
});
