import { generateProtocolForPacient } from "protocols-generator";

jest.mock("uuid", () => {
  return {
    v4: () => {
      return "protocol generated by mock";
    },
  };
});

describe("Protocol Generator Tests", () => {
  it("should create an protocol", async () => {
    const result = generateProtocolForPacient("Pedro", "Silva", true);

    expect(result).toEqual({
      priority: true,
      date: expect.any(Date),
      pacient: "Pedro Silva",
      protocol: "protocol generated by mock",
    });
  });
});
