import { generateProtocolForPacient } from "protocols-generator";

jest.mock("uuid", () => {
  return {
    v4: () => {
      return "protocol generated by mock";
    },
  };
});

describe("calculator tests", () => {
  it("should work", async () => {
    const date = new Date().getTime().toString();

    const result = generateProtocolForPacient("Pedro", "Silva", true);

    expect(result).toEqual({
      priority: true,
      date,
      pacient: "Pedro Silva",
      protocol: "protocol generated by mock",
    });
  });
});
